"""empty message

Revision ID: 03c351d15fd3
Revises: 9261ea6011ce
Create Date: 2025-10-24 21:54:54.166856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c351d15fd3'
down_revision = '9261ea6011ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_info', schema=None) as batch_op:
        batch_op.alter_column('date_joined',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_info', schema=None) as batch_op:
        batch_op.alter_column('date_joined',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
