"""empty message

Revision ID: fb3bc544409d
Revises: 14520a790cb5
Create Date: 2025-11-10 18:12:58.205103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3bc544409d'
down_revision = '14520a790cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trained_models', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trained_models', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
